apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

# Secrets should be created from sops-secrets-operator
# or manually before applying
