---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    env: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    env: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    env: production
